/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiHomeRouteImport } from './routes/api/home'
import { Route as HelpRemoRouteImport } from './routes/help/remo'
import { Route as HelpSwitchbotRouteImport } from './routes/help/switchbot'
import { Route as HelpTuyaRouteImport } from './routes/help/tuya'
import { Route as ApiAlexaSplatRouteImport } from './routes/api/alexa/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOpsBackupRouteImport } from './routes/api/ops/backup'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiStripePortalRouteImport } from './routes/api/stripe/portal'
import { Route as ApiStripeStatusRouteImport } from './routes/api/stripe/status'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeRoute = ApiHomeRouteImport.update({
  id: '/api/home',
  path: '/api/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRemoRoute = HelpRemoRouteImport.update({
  id: '/help/remo',
  path: '/help/remo',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSwitchbotRoute = HelpSwitchbotRouteImport.update({
  id: '/help/switchbot',
  path: '/help/switchbot',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTuyaRoute = HelpTuyaRouteImport.update({
  id: '/help/tuya',
  path: '/help/tuya',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlexaSplatRoute = ApiAlexaSplatRouteImport.update({
  id: '/api/alexa/$',
  path: '/api/alexa/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsBackupRoute = ApiOpsBackupRouteImport.update({
  id: '/api/ops/backup',
  path: '/api/ops/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeStatusRoute = ApiStripeStatusRouteImport.update({
  id: '/api/stripe/status',
  path: '/api/stripe/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rooms': typeof RoomsRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/home': typeof ApiHomeRoute
  '/help/remo': typeof HelpRemoRoute
  '/help/switchbot': typeof HelpSwitchbotRoute
  '/help/tuya': typeof HelpTuyaRoute
  '/api/alexa/$': typeof ApiAlexaSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ops/backup': typeof ApiOpsBackupRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/status': typeof ApiStripeStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rooms': typeof RoomsRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/home': typeof ApiHomeRoute
  '/help/remo': typeof HelpRemoRoute
  '/help/switchbot': typeof HelpSwitchbotRoute
  '/help/tuya': typeof HelpTuyaRoute
  '/api/alexa/$': typeof ApiAlexaSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ops/backup': typeof ApiOpsBackupRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/status': typeof ApiStripeStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rooms': typeof RoomsRoute
  '/scenes': typeof ScenesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/home': typeof ApiHomeRoute
  '/help/remo': typeof HelpRemoRoute
  '/help/switchbot': typeof HelpSwitchbotRoute
  '/help/tuya': typeof HelpTuyaRoute
  '/api/alexa/$': typeof ApiAlexaSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ops/backup': typeof ApiOpsBackupRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/status': typeof ApiStripeStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/rooms'
    | '/scenes'
    | '/settings'
    | '/terms'
    | '/api/home'
    | '/help/remo'
    | '/help/switchbot'
    | '/help/tuya'
    | '/api/alexa/$'
    | '/api/auth/$'
    | '/api/ops/backup'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/status'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/rooms'
    | '/scenes'
    | '/settings'
    | '/terms'
    | '/api/home'
    | '/help/remo'
    | '/help/switchbot'
    | '/help/tuya'
    | '/api/alexa/$'
    | '/api/auth/$'
    | '/api/ops/backup'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/status'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy'
    | '/rooms'
    | '/scenes'
    | '/settings'
    | '/terms'
    | '/api/home'
    | '/help/remo'
    | '/help/switchbot'
    | '/help/tuya'
    | '/api/alexa/$'
    | '/api/auth/$'
    | '/api/ops/backup'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/status'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RoomsRoute: typeof RoomsRoute
  ScenesRoute: typeof ScenesRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiHomeRoute: typeof ApiHomeRoute
  HelpRemoRoute: typeof HelpRemoRoute
  HelpSwitchbotRoute: typeof HelpSwitchbotRoute
  HelpTuyaRoute: typeof HelpTuyaRoute
  ApiAlexaSplatRoute: typeof ApiAlexaSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOpsBackupRoute: typeof ApiOpsBackupRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeStatusRoute: typeof ApiStripeStatusRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/home': {
      id: '/api/home'
      path: '/api/home'
      fullPath: '/api/home'
      preLoaderRoute: typeof ApiHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/remo': {
      id: '/help/remo'
      path: '/help/remo'
      fullPath: '/help/remo'
      preLoaderRoute: typeof HelpRemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/switchbot': {
      id: '/help/switchbot'
      path: '/help/switchbot'
      fullPath: '/help/switchbot'
      preLoaderRoute: typeof HelpSwitchbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/tuya': {
      id: '/help/tuya'
      path: '/help/tuya'
      fullPath: '/help/tuya'
      preLoaderRoute: typeof HelpTuyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alexa/$': {
      id: '/api/alexa/$'
      path: '/api/alexa/$'
      fullPath: '/api/alexa/$'
      preLoaderRoute: typeof ApiAlexaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/backup': {
      id: '/api/ops/backup'
      path: '/api/ops/backup'
      fullPath: '/api/ops/backup'
      preLoaderRoute: typeof ApiOpsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/status': {
      id: '/api/stripe/status'
      path: '/api/stripe/status'
      fullPath: '/api/stripe/status'
      preLoaderRoute: typeof ApiStripeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RoomsRoute: RoomsRoute,
  ScenesRoute: ScenesRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiHomeRoute: ApiHomeRoute,
  HelpRemoRoute: HelpRemoRoute,
  HelpSwitchbotRoute: HelpSwitchbotRoute,
  HelpTuyaRoute: HelpTuyaRoute,
  ApiAlexaSplatRoute: ApiAlexaSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpsBackupRoute: ApiOpsBackupRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeStatusRoute: ApiStripeStatusRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
